version: "3.5"

services:
    db:
        image: postgres:16.2
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=app_data
        volumes:
            - ./database/dev_database_init:/docker-entrypoint-initdb.d

    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - "8080:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=password
